from __future__ import annotations
from datetime import datetime
from typing import Any, Protocol
from transintelligence.core.states import State, StateHistory
from transintelligence.representation.reference_frames import ReferenceFrame

class GeometricReasoner(Protocol):
    def distance(self, x: Any, y: Any) -> float: ...
    def similarity(self, x: Any, y: Any) -> float: ...
    def nearest(self, x: Any, items: list[Any], k: int = 1) -> list[tuple[Any, float]]: ...
class RelativeReasoner(Protocol):
    def evaluate(self, x: Any, reference_frame: ReferenceFrame): ...
    def compare(self, x: Any, y: Any, reference_frame: ReferenceFrame): ...
    def rank(self, items: list[Any], reference_frame: ReferenceFrame): ...
    def sensitivity(self, x: Any, r1: ReferenceFrame, r2: ReferenceFrame): ...
class TemporalReasoner(Protocol):
    def change_points(self, history: StateHistory, key: str) -> list[datetime]: ...
    def joint_change_points(self, history: StateHistory, keys: list[str]) -> list[datetime]: ...
    def regime_segments(self, history: StateHistory, key: str) -> list[Any]: ...
    def compare(self, a: State, b: State) -> dict[str, tuple[Any, Any]]: ...
    def trajectory_distance(self, a: StateHistory, b: StateHistory, key: str) -> float: ...
class CausalReasoner(Protocol):
    def d_separated(self, x: str, y: str, conditioning_set: set[str] | None = None) -> bool: ...
    def satisfies_backdoor_criterion(self, treatment: str, outcome: str, adjustment_set: set[str]) -> bool: ...
class CounterfactualReasoner(Protocol):
    def abduct(self, observed: dict[str, float]) -> dict[str, float]: ...
    def counterfactual(self, observed: dict[str, float], intervention: dict[str, float]) -> dict[str, float]: ...
class Predictor(Protocol):
    def predict(self, state: Any, action: Any) -> Any: ...
class Simulator(Protocol): pass
class Planner(Protocol): pass
class Verifier(Protocol): pass
