from __future__ import annotations
from datetime import datetime
from typing import Any, Protocol
from transintelligence.core.states import State, StateHistory
from transintelligence.representation.reference_frames import ReferenceFrame

class GeometricReasoner(Protocol):
    def distance(self, x: Any, y: Any) -> float: ...
    def similarity(self, x: Any, y: Any) -> float: ...
    def nearest(self, x: Any, items: list[Any], k: int = 1) -> list[tuple[Any, float]]: ...
class RelativeReasoner(Protocol):
    def evaluate(self, x: Any, reference_frame: ReferenceFrame): ...
    def compare(self, x: Any, y: Any, reference_frame: ReferenceFrame): ...
    def rank(self, items: list[Any], reference_frame: ReferenceFrame): ...
    def sensitivity(self, x: Any, r1: ReferenceFrame, r2: ReferenceFrame): ...
class TemporalReasoner(Protocol):
    def change_points(self, history: StateHistory, key: str) -> list[datetime]: ...
    def joint_change_points(self, history: StateHistory, keys: list[str]) -> list[datetime]: ...
    def regime_segments(self, history: StateHistory, key: str) -> list[Any]: ...
    def compare(self, a: State, b: State) -> dict[str, tuple[Any, Any]]: ...
    def trajectory_distance(self, a: StateHistory, b: StateHistory, key: str) -> float: ...
class CausalReasoner(Protocol): pass
class CounterfactualReasoner(Protocol): pass
class Predictor(Protocol): pass
class Simulator(Protocol): pass
class Planner(Protocol): pass
class Verifier(Protocol): pass
