from __future__ import annotations
from typing import Any, Protocol
from transintelligence.representation.reference_frames import ReferenceFrame

class GeometricReasoner(Protocol):
    def distance(self, x: Any, y: Any) -> float: ...
    def similarity(self, x: Any, y: Any) -> float: ...
    def nearest(self, x: Any, items: list[Any], k: int = 1) -> list[tuple[Any, float]]: ...
class RelativeReasoner(Protocol):
    def evaluate(self, x: Any, reference_frame: ReferenceFrame): ...
    def compare(self, x: Any, y: Any, reference_frame: ReferenceFrame): ...
    def rank(self, items: list[Any], reference_frame: ReferenceFrame): ...
    def sensitivity(self, x: Any, r1: ReferenceFrame, r2: ReferenceFrame): ...
class TemporalReasoner(Protocol): pass
class CausalReasoner(Protocol): pass
class CounterfactualReasoner(Protocol): pass
class Predictor(Protocol): pass
class Simulator(Protocol): pass
class Planner(Protocol): pass
class Verifier(Protocol): pass
